language: node_js
node_js: stable

install:
  - npm install

script:
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "MKFMIKU"
  - git config user.email "kfm@clfstudio.com"
  - git add .
  - git commit -m "Update Posts"
  - git push --force --quiet "https://${token}@${GH_REF}" master

branches:
  only:
    - hexo

env:
 global:
   - GH_REF: github.com/CLF-Vision/CLF-Vision.github.io.git